### ISSUE TITLE
Link to event sourcing in Readme is broken.

### ISSUE THREAD

**Issue by frddl** [spatie/larabank-aggregates#28]
Basicly, the title says it all. I was not sure if the correct link was supposed to be `event-sourcing-laravel.com` , so didn't send a PR.

**Comment by freekmurze** [comment]
I'm not sure which link you mean, they all seem correct to me. Feel free to send a PR to change it to event-sourcing-laravel.com

**Comment by frddl** [comment]
I meant the link that was supposed to go to the documentation of `laravel-event-projector`
