### ISSUE TITLE
Method onEvent() Signature In Projectors Doesn't Match With 2.6

### ISSUE THREAD

**Issue by warren32** [spatie/larabank-aggregates#3]
PR #139 on spatie/laravel-event-projector appears to have changed the method signatures for the event handler methods inside the Projectors.  

In `app/Domain/Account/Projectors/AccountProjector.php`

```
public function onAccountCreated(AccountCreated $event, string $aggregateUuid)
    {
        Account::create([
            'uuid' => $aggregateUuid,
            'name' => $event->name,
            'user_id' => $event->userId,
        ]);
    }
```

But this should be (for v2.6 of event-projector)
```
public function onAccountCreated(AccountCreated $event, StoredEvent $storedEvent, string $aggregateUuid)
    {
        Account::create([
            'uuid' => $aggregateUuid,
            'name' => $event->name,
            'user_id' => $event->userId,
        ]);
    }
```

**Comment by freekmurze** [comment]
I'm thinking the old code should just work as well. The method injection is based on the name of the variable too.

**Comment by warren32** [comment]
Ah yes, that makes sense now.  I guess Laravel's service container will help here.  I think I had seen the docs on `laravel-event-projector` here: https://docs.spatie.be/laravel-event-projector/v2/using-reactors/creating-and-configuring-reactors#getting-the-uuid-of-an-event
Where it described 

> "The order of the parameters giving to an event handling method like onMoneyAdded. We'll simply pass the uuid to any arguments named **$uuid.**"

I may be reading this incorrectly but should this be $aggregateUuid? If so, I can submit a PR on the `laravel-event-projector` docs. 

Thanks for some great examples here and a great package for getting started with event sourcing.
